apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  workspaces:
    - name: source
      description: "Workspace containing the source code to test"
  steps:
    - name: run-tests
      image: python:3.11
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo "Running unit tests with nose..."
        pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        pip install nose
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
